name: Actions 😎

on: [push]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'matbuha'
          git config --global user.email 'arielbenzikri@gmail.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Committing changes from GitHub Actions"
          git push

      - name: Clean up Docker space
        run: |
          docker system prune -af
          sudo rm -rf /usr/local/share/dotnet
          sudo rm -rf /usr/share/swift

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

  # deployPages:
  #   needs: build
  #   name: Deploy to Itch.io 🚀
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - uses: actions/download-artifact@v4.1.0
  #       with:
  #         name: build-WebGL
  #         path: build

  #     - name: Display structure of root files
  #       run: ls -R
  #       working-directory: build/WebGL

  #     - name: Deploy 🚀
  #       uses: JamesIves/github-pages-deploy-action@4.1.4
  #       with:
  #         branch: itch-io
  #         folder: build/WebGL
          
  #     - uses: manleydev/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
  #         CHANNEL: HTML
  #         ITCH_GAME: Kitchen-Madness
  #         ITCH_USER: Erzelman
  #         BRANCH: itch-io
  #         PACKAGE: build/WebGL