on: [push]

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64 # For Windows Build
          - Android # For Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # File integrity check
      - name: Verify File Integrity
        run: sha256sum -c Assets/Scenes/GameScene/checksums.txt || exit 1

      - name: Unity - Builder
        uses: game-ci/unity-builder@v4.1.3
        with:
          unityVersion: '2022.3.13f1' # Specify your Unity version
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: MyGame
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build/${{ matrix.targetPlatform }}/*

      - name: Clean up
        run: rm -rf build
