name: Unity Build Workflow

on: [push]

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # File integrity check
    - name: Verify File Integrity
      run: sha256sum -c Assets/Scenes/GameScene/checksums.txt || exit 1

    - name: Build Unity Project
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: '2022.3.13f1' # Specify your Unity version
        targetPlatform: ${{ matrix.targetPlatform }}
        buildName: MyGame
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build/${{ matrix.targetPlatform }}/*

    - name: Clean up
      run: rm -rf build

  strategy:
    matrix:
      targetPlatform:
        - StandaloneWindows64 # For Windows Build
        - Android # For Android Build
